version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: SETUP
          command: npm i && npm run setup
      - run:
          name: LINT
          command: npm run lint:nofix
      - run:
          name: JEST
          command: npm run test
